/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QGroupBox *groupBox1;
    QGroupBox *gbox0;
    QSlider *pwmBar0;
    QSlider *timeBar0;
    QPushButton *pwmBtn;
    QPushButton *timeBtn;
    QSpinBox *pwmSpinBox0;
    QSpinBox *timeSpinBox0;
    QLabel *label_3;
    QGroupBox *gbox1;
    QSlider *pwmBar1;
    QSlider *timeBar1;
    QPushButton *pwmBtn_2;
    QPushButton *timeBtn_2;
    QSpinBox *pwmSpinBox1;
    QSpinBox *timeSpinBox1;
    QGroupBox *gbox2;
    QSlider *pwmBar2;
    QSlider *timeBar2;
    QPushButton *pwmBtn_3;
    QPushButton *timeBtn_3;
    QSpinBox *pwmSpinBox2;
    QSpinBox *timeSpinBox2;
    QGroupBox *gbox4;
    QSlider *pwmBar4;
    QSlider *timeBar4;
    QPushButton *pwmBtn_6;
    QPushButton *timeBtn_6;
    QSpinBox *pwmSpinBox4;
    QSpinBox *timeSpinBox4;
    QGroupBox *gbox5;
    QSlider *pwmBar5;
    QSlider *timeBar5;
    QPushButton *pwmBtn_7;
    QPushButton *timeBtn_7;
    QSpinBox *pwmSpinBox5;
    QSpinBox *timeSpinBox5;
    QLabel *label_8;
    QSpinBox *timeSpinBoxAll;
    QSlider *timeSliderAll;
    QPushButton *pwmFocus;
    QGroupBox *gbox3;
    QSlider *pwmBar3;
    QSlider *timeBar3;
    QPushButton *pwmBtn_4;
    QPushButton *timeBtn_4;
    QSpinBox *pwmSpinBox3;
    QSpinBox *timeSpinBox3;
    QGroupBox *groupBox0;
    QPushButton *pbtnOpen;
    QComboBox *cmbSeriaNum;
    QComboBox *cmbRate;
    QLabel *label;
    QLabel *label_2;
    QGroupBox *groupBox4;
    QTextBrowser *txtCmd;
    QPushButton *pbtnClearTxtCmd;
    QGroupBox *groupBox3;
    QPushButton *pbtnSend;
    QLineEdit *edtCmdSend;
    QGroupBox *groupBox2;
    QTabWidget *tabWidget;
    QWidget *tab;
    QListWidget *listWidget;
    QPushButton *pbtnAddGroup;
    QPushButton *pbtnDelGroup;
    QPushButton *pbtnSaveDjAction;
    QCheckBox *chkDjStyle;
    QFrame *frame0;
    QLabel *lblHttp;
    QPushButton *pbtnEaDnAc;
    QGroupBox *groupBox5;
    QFrame *frame_3;
    QPushButton *pbtnDoAction;
    QLabel *label_5;
    QSpinBox *spinBoxDjStart;
    QSpinBox *spinBoxDjEnd;
    QLabel *label_4;
    QSpinBox *spinBoxDoTimes;
    QPushButton *pbtnRdDnAc;
    QPushButton *SimBtn;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(710, 699);
        MainWindow->setMouseTracking(false);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        groupBox1 = new QGroupBox(centralWidget);
        groupBox1->setObjectName(QStringLiteral("groupBox1"));
        groupBox1->setGeometry(QRect(10, 180, 691, 211));
        groupBox1->setCheckable(false);
        groupBox1->setChecked(false);
        gbox0 = new QGroupBox(groupBox1);
        gbox0->setObjectName(QStringLiteral("gbox0"));
        gbox0->setGeometry(QRect(10, 20, 161, 81));
        gbox0->setMouseTracking(false);
        gbox0->setAlignment(Qt::AlignCenter);
        gbox0->setFlat(true);
        gbox0->setCheckable(true);
        gbox0->setChecked(false);
        pwmBar0 = new QSlider(gbox0);
        pwmBar0->setObjectName(QStringLiteral("pwmBar0"));
        pwmBar0->setGeometry(QRect(50, 20, 61, 19));
        pwmBar0->setMinimum(500);
        pwmBar0->setMaximum(2500);
        pwmBar0->setValue(1500);
        pwmBar0->setOrientation(Qt::Horizontal);
        timeBar0 = new QSlider(gbox0);
        timeBar0->setObjectName(QStringLiteral("timeBar0"));
        timeBar0->setGeometry(QRect(50, 50, 61, 19));
        timeBar0->setMinimum(20);
        timeBar0->setMaximum(10000);
        timeBar0->setSingleStep(1);
        timeBar0->setPageStep(20);
        timeBar0->setValue(200);
        timeBar0->setOrientation(Qt::Horizontal);
        pwmBtn = new QPushButton(gbox0);
        pwmBtn->setObjectName(QStringLiteral("pwmBtn"));
        pwmBtn->setGeometry(QRect(0, 20, 41, 23));
        timeBtn = new QPushButton(gbox0);
        timeBtn->setObjectName(QStringLiteral("timeBtn"));
        timeBtn->setGeometry(QRect(0, 50, 41, 23));
        pwmSpinBox0 = new QSpinBox(gbox0);
        pwmSpinBox0->setObjectName(QStringLiteral("pwmSpinBox0"));
        pwmSpinBox0->setGeometry(QRect(110, 20, 51, 22));
        pwmSpinBox0->setMinimum(500);
        pwmSpinBox0->setMaximum(2500);
        pwmSpinBox0->setSingleStep(25);
        pwmSpinBox0->setValue(1500);
        timeSpinBox0 = new QSpinBox(gbox0);
        timeSpinBox0->setObjectName(QStringLiteral("timeSpinBox0"));
        timeSpinBox0->setGeometry(QRect(110, 50, 51, 22));
        timeSpinBox0->setMinimum(20);
        timeSpinBox0->setMaximum(10000);
        timeSpinBox0->setSingleStep(20);
        timeSpinBox0->setValue(200);
        timeSpinBox0->setDisplayIntegerBase(10);
        label_3 = new QLabel(groupBox1);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 180, 211, 16));
        gbox1 = new QGroupBox(groupBox1);
        gbox1->setObjectName(QStringLiteral("gbox1"));
        gbox1->setGeometry(QRect(260, 20, 161, 81));
        gbox1->setMouseTracking(false);
        gbox1->setAlignment(Qt::AlignCenter);
        gbox1->setFlat(true);
        gbox1->setCheckable(true);
        gbox1->setChecked(false);
        pwmBar1 = new QSlider(gbox1);
        pwmBar1->setObjectName(QStringLiteral("pwmBar1"));
        pwmBar1->setGeometry(QRect(50, 20, 61, 19));
        pwmBar1->setMinimum(500);
        pwmBar1->setMaximum(2500);
        pwmBar1->setValue(1500);
        pwmBar1->setOrientation(Qt::Horizontal);
        timeBar1 = new QSlider(gbox1);
        timeBar1->setObjectName(QStringLiteral("timeBar1"));
        timeBar1->setGeometry(QRect(50, 50, 61, 19));
        timeBar1->setMinimum(20);
        timeBar1->setMaximum(10000);
        timeBar1->setSingleStep(1);
        timeBar1->setPageStep(20);
        timeBar1->setValue(200);
        timeBar1->setOrientation(Qt::Horizontal);
        pwmBtn_2 = new QPushButton(gbox1);
        pwmBtn_2->setObjectName(QStringLiteral("pwmBtn_2"));
        pwmBtn_2->setGeometry(QRect(0, 20, 41, 23));
        timeBtn_2 = new QPushButton(gbox1);
        timeBtn_2->setObjectName(QStringLiteral("timeBtn_2"));
        timeBtn_2->setGeometry(QRect(0, 50, 41, 23));
        pwmSpinBox1 = new QSpinBox(gbox1);
        pwmSpinBox1->setObjectName(QStringLiteral("pwmSpinBox1"));
        pwmSpinBox1->setGeometry(QRect(110, 20, 51, 22));
        pwmSpinBox1->setMinimum(500);
        pwmSpinBox1->setMaximum(2500);
        pwmSpinBox1->setSingleStep(25);
        pwmSpinBox1->setValue(1500);
        timeSpinBox1 = new QSpinBox(gbox1);
        timeSpinBox1->setObjectName(QStringLiteral("timeSpinBox1"));
        timeSpinBox1->setGeometry(QRect(110, 50, 51, 22));
        timeSpinBox1->setMinimum(20);
        timeSpinBox1->setMaximum(10000);
        timeSpinBox1->setSingleStep(20);
        timeSpinBox1->setValue(200);
        timeSpinBox1->setDisplayIntegerBase(10);
        gbox2 = new QGroupBox(groupBox1);
        gbox2->setObjectName(QStringLiteral("gbox2"));
        gbox2->setGeometry(QRect(480, 20, 161, 81));
        gbox2->setMouseTracking(false);
        gbox2->setAlignment(Qt::AlignCenter);
        gbox2->setFlat(true);
        gbox2->setCheckable(true);
        gbox2->setChecked(false);
        pwmBar2 = new QSlider(gbox2);
        pwmBar2->setObjectName(QStringLiteral("pwmBar2"));
        pwmBar2->setGeometry(QRect(50, 20, 61, 19));
        pwmBar2->setMinimum(500);
        pwmBar2->setMaximum(2500);
        pwmBar2->setValue(1500);
        pwmBar2->setOrientation(Qt::Horizontal);
        timeBar2 = new QSlider(gbox2);
        timeBar2->setObjectName(QStringLiteral("timeBar2"));
        timeBar2->setGeometry(QRect(50, 50, 61, 19));
        timeBar2->setMinimum(20);
        timeBar2->setMaximum(10000);
        timeBar2->setSingleStep(1);
        timeBar2->setPageStep(20);
        timeBar2->setValue(200);
        timeBar2->setOrientation(Qt::Horizontal);
        pwmBtn_3 = new QPushButton(gbox2);
        pwmBtn_3->setObjectName(QStringLiteral("pwmBtn_3"));
        pwmBtn_3->setGeometry(QRect(0, 20, 41, 23));
        timeBtn_3 = new QPushButton(gbox2);
        timeBtn_3->setObjectName(QStringLiteral("timeBtn_3"));
        timeBtn_3->setGeometry(QRect(0, 50, 41, 23));
        pwmSpinBox2 = new QSpinBox(gbox2);
        pwmSpinBox2->setObjectName(QStringLiteral("pwmSpinBox2"));
        pwmSpinBox2->setGeometry(QRect(110, 20, 51, 22));
        pwmSpinBox2->setMinimum(500);
        pwmSpinBox2->setMaximum(2500);
        pwmSpinBox2->setSingleStep(25);
        pwmSpinBox2->setValue(1500);
        timeSpinBox2 = new QSpinBox(gbox2);
        timeSpinBox2->setObjectName(QStringLiteral("timeSpinBox2"));
        timeSpinBox2->setGeometry(QRect(110, 50, 51, 22));
        timeSpinBox2->setMinimum(20);
        timeSpinBox2->setMaximum(10000);
        timeSpinBox2->setSingleStep(20);
        timeSpinBox2->setValue(200);
        timeSpinBox2->setDisplayIntegerBase(10);
        gbox4 = new QGroupBox(groupBox1);
        gbox4->setObjectName(QStringLiteral("gbox4"));
        gbox4->setGeometry(QRect(260, 100, 161, 81));
        gbox4->setMouseTracking(false);
        gbox4->setAlignment(Qt::AlignCenter);
        gbox4->setFlat(true);
        gbox4->setCheckable(true);
        gbox4->setChecked(false);
        pwmBar4 = new QSlider(gbox4);
        pwmBar4->setObjectName(QStringLiteral("pwmBar4"));
        pwmBar4->setGeometry(QRect(50, 20, 61, 19));
        pwmBar4->setMinimum(500);
        pwmBar4->setMaximum(2500);
        pwmBar4->setValue(1500);
        pwmBar4->setOrientation(Qt::Horizontal);
        timeBar4 = new QSlider(gbox4);
        timeBar4->setObjectName(QStringLiteral("timeBar4"));
        timeBar4->setGeometry(QRect(50, 50, 61, 19));
        timeBar4->setMinimum(20);
        timeBar4->setMaximum(10000);
        timeBar4->setSingleStep(1);
        timeBar4->setPageStep(20);
        timeBar4->setValue(200);
        timeBar4->setSliderPosition(200);
        timeBar4->setOrientation(Qt::Horizontal);
        pwmBtn_6 = new QPushButton(gbox4);
        pwmBtn_6->setObjectName(QStringLiteral("pwmBtn_6"));
        pwmBtn_6->setGeometry(QRect(0, 20, 41, 23));
        timeBtn_6 = new QPushButton(gbox4);
        timeBtn_6->setObjectName(QStringLiteral("timeBtn_6"));
        timeBtn_6->setGeometry(QRect(0, 50, 41, 23));
        pwmSpinBox4 = new QSpinBox(gbox4);
        pwmSpinBox4->setObjectName(QStringLiteral("pwmSpinBox4"));
        pwmSpinBox4->setGeometry(QRect(110, 20, 51, 22));
        pwmSpinBox4->setMinimum(500);
        pwmSpinBox4->setMaximum(2500);
        pwmSpinBox4->setSingleStep(25);
        pwmSpinBox4->setValue(1500);
        timeSpinBox4 = new QSpinBox(gbox4);
        timeSpinBox4->setObjectName(QStringLiteral("timeSpinBox4"));
        timeSpinBox4->setGeometry(QRect(110, 50, 51, 22));
        timeSpinBox4->setMinimum(20);
        timeSpinBox4->setMaximum(10000);
        timeSpinBox4->setSingleStep(20);
        timeSpinBox4->setValue(200);
        timeSpinBox4->setDisplayIntegerBase(10);
        gbox5 = new QGroupBox(groupBox1);
        gbox5->setObjectName(QStringLiteral("gbox5"));
        gbox5->setGeometry(QRect(480, 100, 161, 81));
        gbox5->setMouseTracking(false);
        gbox5->setAlignment(Qt::AlignCenter);
        gbox5->setFlat(true);
        gbox5->setCheckable(true);
        gbox5->setChecked(false);
        pwmBar5 = new QSlider(gbox5);
        pwmBar5->setObjectName(QStringLiteral("pwmBar5"));
        pwmBar5->setGeometry(QRect(50, 20, 61, 19));
        pwmBar5->setMinimum(500);
        pwmBar5->setMaximum(2500);
        pwmBar5->setValue(1500);
        pwmBar5->setOrientation(Qt::Horizontal);
        timeBar5 = new QSlider(gbox5);
        timeBar5->setObjectName(QStringLiteral("timeBar5"));
        timeBar5->setGeometry(QRect(50, 50, 61, 19));
        timeBar5->setMinimum(20);
        timeBar5->setMaximum(10000);
        timeBar5->setSingleStep(1);
        timeBar5->setPageStep(20);
        timeBar5->setValue(200);
        timeBar5->setOrientation(Qt::Horizontal);
        pwmBtn_7 = new QPushButton(gbox5);
        pwmBtn_7->setObjectName(QStringLiteral("pwmBtn_7"));
        pwmBtn_7->setGeometry(QRect(0, 20, 41, 23));
        timeBtn_7 = new QPushButton(gbox5);
        timeBtn_7->setObjectName(QStringLiteral("timeBtn_7"));
        timeBtn_7->setGeometry(QRect(0, 50, 41, 23));
        pwmSpinBox5 = new QSpinBox(gbox5);
        pwmSpinBox5->setObjectName(QStringLiteral("pwmSpinBox5"));
        pwmSpinBox5->setGeometry(QRect(110, 20, 51, 22));
        pwmSpinBox5->setMinimum(500);
        pwmSpinBox5->setMaximum(2500);
        pwmSpinBox5->setSingleStep(25);
        pwmSpinBox5->setValue(1500);
        timeSpinBox5 = new QSpinBox(gbox5);
        timeSpinBox5->setObjectName(QStringLiteral("timeSpinBox5"));
        timeSpinBox5->setGeometry(QRect(110, 50, 51, 22));
        timeSpinBox5->setMinimum(20);
        timeSpinBox5->setMaximum(10000);
        timeSpinBox5->setSingleStep(20);
        timeSpinBox5->setValue(200);
        timeSpinBox5->setDisplayIntegerBase(10);
        label_8 = new QLabel(groupBox1);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(210, 180, 101, 21));
        timeSpinBoxAll = new QSpinBox(groupBox1);
        timeSpinBoxAll->setObjectName(QStringLiteral("timeSpinBoxAll"));
        timeSpinBoxAll->setGeometry(QRect(460, 180, 51, 22));
        timeSpinBoxAll->setMinimum(20);
        timeSpinBoxAll->setMaximum(10000);
        timeSpinBoxAll->setSingleStep(1);
        timeSpinBoxAll->setValue(200);
        timeSpinBoxAll->setDisplayIntegerBase(10);
        timeSliderAll = new QSlider(groupBox1);
        timeSliderAll->setObjectName(QStringLiteral("timeSliderAll"));
        timeSliderAll->setGeometry(QRect(300, 180, 151, 19));
        timeSliderAll->setMinimum(20);
        timeSliderAll->setMaximum(10000);
        timeSliderAll->setSingleStep(20);
        timeSliderAll->setPageStep(1);
        timeSliderAll->setValue(200);
        timeSliderAll->setOrientation(Qt::Horizontal);
        pwmFocus = new QPushButton(groupBox1);
        pwmFocus->setObjectName(QStringLiteral("pwmFocus"));
        pwmFocus->setGeometry(QRect(520, 180, 81, 23));
        gbox3 = new QGroupBox(groupBox1);
        gbox3->setObjectName(QStringLiteral("gbox3"));
        gbox3->setGeometry(QRect(10, 100, 161, 81));
        gbox3->setMouseTracking(false);
        gbox3->setAlignment(Qt::AlignCenter);
        gbox3->setFlat(true);
        gbox3->setCheckable(true);
        gbox3->setChecked(false);
        pwmBar3 = new QSlider(gbox3);
        pwmBar3->setObjectName(QStringLiteral("pwmBar3"));
        pwmBar3->setGeometry(QRect(50, 20, 61, 19));
        pwmBar3->setMinimum(500);
        pwmBar3->setMaximum(2500);
        pwmBar3->setValue(1500);
        pwmBar3->setOrientation(Qt::Horizontal);
        timeBar3 = new QSlider(gbox3);
        timeBar3->setObjectName(QStringLiteral("timeBar3"));
        timeBar3->setGeometry(QRect(50, 50, 61, 19));
        timeBar3->setMinimum(20);
        timeBar3->setMaximum(10000);
        timeBar3->setSingleStep(1);
        timeBar3->setPageStep(20);
        timeBar3->setValue(200);
        timeBar3->setOrientation(Qt::Horizontal);
        pwmBtn_4 = new QPushButton(gbox3);
        pwmBtn_4->setObjectName(QStringLiteral("pwmBtn_4"));
        pwmBtn_4->setGeometry(QRect(0, 20, 41, 23));
        timeBtn_4 = new QPushButton(gbox3);
        timeBtn_4->setObjectName(QStringLiteral("timeBtn_4"));
        timeBtn_4->setGeometry(QRect(0, 50, 41, 23));
        pwmSpinBox3 = new QSpinBox(gbox3);
        pwmSpinBox3->setObjectName(QStringLiteral("pwmSpinBox3"));
        pwmSpinBox3->setGeometry(QRect(110, 20, 51, 22));
        pwmSpinBox3->setMinimum(500);
        pwmSpinBox3->setMaximum(2500);
        pwmSpinBox3->setSingleStep(25);
        pwmSpinBox3->setValue(1500);
        timeSpinBox3 = new QSpinBox(gbox3);
        timeSpinBox3->setObjectName(QStringLiteral("timeSpinBox3"));
        timeSpinBox3->setGeometry(QRect(110, 50, 51, 22));
        timeSpinBox3->setMinimum(20);
        timeSpinBox3->setMaximum(10000);
        timeSpinBox3->setSingleStep(20);
        timeSpinBox3->setValue(200);
        timeSpinBox3->setDisplayIntegerBase(10);
        groupBox0 = new QGroupBox(centralWidget);
        groupBox0->setObjectName(QStringLiteral("groupBox0"));
        groupBox0->setGeometry(QRect(10, 10, 191, 161));
        pbtnOpen = new QPushButton(groupBox0);
        pbtnOpen->setObjectName(QStringLiteral("pbtnOpen"));
        pbtnOpen->setGeometry(QRect(20, 110, 151, 41));
        cmbSeriaNum = new QComboBox(groupBox0);
        cmbSeriaNum->setObjectName(QStringLiteral("cmbSeriaNum"));
        cmbSeriaNum->setGeometry(QRect(90, 20, 81, 22));
        cmbRate = new QComboBox(groupBox0);
        cmbRate->setObjectName(QStringLiteral("cmbRate"));
        cmbRate->setGeometry(QRect(90, 70, 81, 22));
        label = new QLabel(groupBox0);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 20, 61, 21));
        label_2 = new QLabel(groupBox0);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 70, 61, 21));
        groupBox4 = new QGroupBox(centralWidget);
        groupBox4->setObjectName(QStringLiteral("groupBox4"));
        groupBox4->setGeometry(QRect(210, 10, 491, 91));
        txtCmd = new QTextBrowser(groupBox4);
        txtCmd->setObjectName(QStringLiteral("txtCmd"));
        txtCmd->setGeometry(QRect(10, 20, 421, 61));
        pbtnClearTxtCmd = new QPushButton(groupBox4);
        pbtnClearTxtCmd->setObjectName(QStringLiteral("pbtnClearTxtCmd"));
        pbtnClearTxtCmd->setGeometry(QRect(440, 20, 41, 61));
        groupBox3 = new QGroupBox(centralWidget);
        groupBox3->setObjectName(QStringLiteral("groupBox3"));
        groupBox3->setGeometry(QRect(210, 110, 491, 61));
        pbtnSend = new QPushButton(groupBox3);
        pbtnSend->setObjectName(QStringLiteral("pbtnSend"));
        pbtnSend->setGeometry(QRect(400, 20, 81, 31));
        edtCmdSend = new QLineEdit(groupBox3);
        edtCmdSend->setObjectName(QStringLiteral("edtCmdSend"));
        edtCmdSend->setGeometry(QRect(10, 19, 381, 31));
        groupBox2 = new QGroupBox(centralWidget);
        groupBox2->setObjectName(QStringLiteral("groupBox2"));
        groupBox2->setGeometry(QRect(10, 400, 691, 161));
        tabWidget = new QTabWidget(groupBox2);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 20, 591, 131));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        listWidget = new QListWidget(tab);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(0, 0, 591, 111));
        tabWidget->addTab(tab, QString());
        pbtnAddGroup = new QPushButton(groupBox2);
        pbtnAddGroup->setObjectName(QStringLiteral("pbtnAddGroup"));
        pbtnAddGroup->setGeometry(QRect(610, 40, 75, 31));
        pbtnDelGroup = new QPushButton(groupBox2);
        pbtnDelGroup->setObjectName(QStringLiteral("pbtnDelGroup"));
        pbtnDelGroup->setGeometry(QRect(610, 80, 75, 31));
        pbtnSaveDjAction = new QPushButton(groupBox2);
        pbtnSaveDjAction->setObjectName(QStringLiteral("pbtnSaveDjAction"));
        pbtnSaveDjAction->setGeometry(QRect(610, 120, 75, 31));
        chkDjStyle = new QCheckBox(groupBox2);
        chkDjStyle->setObjectName(QStringLiteral("chkDjStyle"));
        chkDjStyle->setGeometry(QRect(380, 10, 161, 20));
        frame0 = new QFrame(centralWidget);
        frame0->setObjectName(QStringLiteral("frame0"));
        frame0->setGeometry(QRect(10, 640, 691, 31));
        frame0->setFrameShape(QFrame::StyledPanel);
        frame0->setFrameShadow(QFrame::Raised);
        lblHttp = new QLabel(frame0);
        lblHttp->setObjectName(QStringLiteral("lblHttp"));
        lblHttp->setGeometry(QRect(10, 0, 191, 31));
        lblHttp->setStyleSheet(QString::fromUtf8("font: 75 14pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblHttp->setOpenExternalLinks(true);
        pbtnEaDnAc = new QPushButton(frame0);
        pbtnEaDnAc->setObjectName(QStringLiteral("pbtnEaDnAc"));
        pbtnEaDnAc->setGeometry(QRect(600, 0, 81, 31));
        groupBox5 = new QGroupBox(centralWidget);
        groupBox5->setObjectName(QStringLiteral("groupBox5"));
        groupBox5->setGeometry(QRect(10, 570, 691, 61));
        frame_3 = new QFrame(groupBox5);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(460, 10, 231, 51));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        pbtnDoAction = new QPushButton(frame_3);
        pbtnDoAction->setObjectName(QStringLiteral("pbtnDoAction"));
        pbtnDoAction->setGeometry(QRect(130, 20, 101, 31));
        label_5 = new QLabel(frame_3);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 0, 41, 51));
        spinBoxDjStart = new QSpinBox(frame_3);
        spinBoxDjStart->setObjectName(QStringLiteral("spinBoxDjStart"));
        spinBoxDjStart->setGeometry(QRect(80, 0, 42, 21));
        spinBoxDjEnd = new QSpinBox(frame_3);
        spinBoxDjEnd->setObjectName(QStringLiteral("spinBoxDjEnd"));
        spinBoxDjEnd->setGeometry(QRect(80, 30, 42, 21));
        label_4 = new QLabel(frame_3);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(130, 0, 61, 16));
        spinBoxDoTimes = new QSpinBox(frame_3);
        spinBoxDoTimes->setObjectName(QStringLiteral("spinBoxDoTimes"));
        spinBoxDoTimes->setGeometry(QRect(190, 0, 42, 16));
        pbtnRdDnAc = new QPushButton(groupBox5);
        pbtnRdDnAc->setObjectName(QStringLiteral("pbtnRdDnAc"));
        pbtnRdDnAc->setGeometry(QRect(150, 20, 141, 31));
        SimBtn = new QPushButton(groupBox5);
        SimBtn->setObjectName(QStringLiteral("SimBtn"));
        SimBtn->setGeometry(QRect(20, 20, 111, 31));
        MainWindow->setCentralWidget(centralWidget);
        groupBox0->raise();
        groupBox1->raise();
        groupBox4->raise();
        groupBox3->raise();
        groupBox2->raise();
        frame0->raise();
        groupBox5->raise();
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        cmbSeriaNum->setCurrentIndex(-1);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Robotic Arm Controller -- Xiaotian Bai", 0));
        groupBox1->setTitle(QApplication::translate("MainWindow", "Servo Control Panel\357\274\210Pulse width range 500-2500us, default width is 1500us, Time refers to rotation time\357\274\211", 0));
        gbox0->setTitle(QApplication::translate("MainWindow", "Servo 0", 0));
        pwmBtn->setText(QApplication::translate("MainWindow", "Width", 0));
        timeBtn->setText(QApplication::translate("MainWindow", "Time", 0));
        label_3->setText(QApplication::translate("MainWindow", "Width Unit: us, Time Unit: ms", 0));
        gbox1->setTitle(QApplication::translate("MainWindow", "Servo 1", 0));
        pwmBtn_2->setText(QApplication::translate("MainWindow", "Width", 0));
        timeBtn_2->setText(QApplication::translate("MainWindow", "Time", 0));
        gbox2->setTitle(QApplication::translate("MainWindow", "Servo 2", 0));
        pwmBtn_3->setText(QApplication::translate("MainWindow", "Width", 0));
        timeBtn_3->setText(QApplication::translate("MainWindow", "Time", 0));
        gbox4->setTitle(QApplication::translate("MainWindow", "Servo 4", 0));
        pwmBtn_6->setText(QApplication::translate("MainWindow", "Width", 0));
        timeBtn_6->setText(QApplication::translate("MainWindow", "Time", 0));
        gbox5->setTitle(QApplication::translate("MainWindow", "Servo 5", 0));
        pwmBtn_7->setText(QApplication::translate("MainWindow", "Width", 0));
        timeBtn_7->setText(QApplication::translate("MainWindow", "Time", 0));
        label_8->setText(QApplication::translate("MainWindow", "Time for all servos", 0));
        pwmFocus->setText(QApplication::translate("MainWindow", "Reset Width", 0));
        gbox3->setTitle(QApplication::translate("MainWindow", "Servo 3", 0));
        pwmBtn_4->setText(QApplication::translate("MainWindow", "Width", 0));
        timeBtn_4->setText(QApplication::translate("MainWindow", "Time", 0));
        groupBox0->setTitle(QString());
        pbtnOpen->setText(QApplication::translate("MainWindow", "Open Port", 0));
        label->setText(QApplication::translate("MainWindow", "Serial Port:", 0));
        label_2->setText(QApplication::translate("MainWindow", "Baud Rate:", 0));
        groupBox4->setTitle(QApplication::translate("MainWindow", "Incoming Feedback", 0));
        pbtnClearTxtCmd->setText(QApplication::translate("MainWindow", "Clear", 0));
        groupBox3->setTitle(QApplication::translate("MainWindow", "Outgoing Command (Test, not safe to use)", 0));
        pbtnSend->setText(QApplication::translate("MainWindow", "Send", 0));
        groupBox2->setTitle(QApplication::translate("MainWindow", "Action Recorder (Use the Control Panel and the Add button to record actions and then execute)", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Tab 1", 0));
        pbtnAddGroup->setText(QApplication::translate("MainWindow", "Add", 0));
        pbtnDelGroup->setText(QApplication::translate("MainWindow", "Delete", 0));
        pbtnSaveDjAction->setText(QApplication::translate("MainWindow", "Clear", 0));
        chkDjStyle->setText(QApplication::translate("MainWindow", "Record Status of Idle Servos", 0));
        lblHttp->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Gradutation Project -- Xiaotian Bai</span></p></body></html>", 0));
        pbtnEaDnAc->setText(QApplication::translate("MainWindow", "Reset Servos", 0));
        groupBox5->setTitle(QString());
        pbtnDoAction->setText(QApplication::translate("MainWindow", "Execute", 0));
        label_5->setText(QApplication::translate("MainWindow", "Start#\n"
"\n"
"End#", 0));
        label_4->setText(QApplication::translate("MainWindow", "Loop#", 0));
        pbtnRdDnAc->setText(QApplication::translate("MainWindow", "Read Actions from File", 0));
        SimBtn->setText(QApplication::translate("MainWindow", "Simulator", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
